version: '3'

networks:
  demo:

volumes:
  yb-node-1:
  yb-node-2:
  yb-node-3:

services:
  yb-node-1:
#    build: yb
    image:  ghcr.io/yogendra/yugabyte:2.18.0.1-b4
    container_name: yb-node-1
    hostname: yb-node-1
    networks:
      - demo
    volumes:
      - yb-node-1:/home/yugabyte/yb-data
    command: [ "/home/yugabyte/yb-software/bin/yugabyted",
               "start",
               "--background=false",
               "--insecure",
               "--base_dir=/home/yugabyte/yb-data",
               "--cloud_location=docker.local.zone1",
               "--fault_tolerance=zone"

    ]
    ports:
      - "7000:7000"
      - "9000:7000"
      - "5433:5433"
      - "9042:9042"
      - "15433:15433"

  yb-node-2:
#    build: yb
    image:  ghcr.io/yogendra/yugabyte:2.18.0.1-b4
    container_name: yb-node-2
    hostname: yb-node-2
    networks:
    - demo

    volumes:
      - yb-node-2:/home/yugabyte/yb-data
    command: [ "/home/yugabyte/yb-software/bin/yugabyted",
               "start",
               "--background=false",
               "--insecure",
               "--base_dir=/home/yugabyte/yb-data",
               "--join=yb-node-1",
               "--cloud_location=docker.local.zone2",
               "--fault_tolerance=zone"
    ]
    depends_on:
      - yb-node-1


  yb-node-3:
#    build: yb
    image:  ghcr.io/yogendra/yugabyte:2.18.0.1-b4
    container_name: yb-node-3
    hostname: yb-node-3
    networks:
    - demo

    volumes:
      - yb-node-3:/home/yugabyte/yb-data
    command: [ "/home/yugabyte/yb-software/bin/yugabyted",
               "start",
               "--background=false",
               "--insecure",
               "--base_dir=/home/yugabyte/yb-data",
               "--join=yb-node-1",
               "--cloud_location=docker.local.zone3",
               "--fault_tolerance=zone"
    ]
    depends_on:
      - yb-node-1

  payment-api:
#    build: ../..
    image: ghcr.io/yogendra/yb-payment-api:latest
    container_name: payment-api
    hostname: payment-api
    networks:
    - demo

    environment:
      - YB_HOST=yb-node-1
    depends_on:
      - yb-node-1
      - yb-node-2
      - yb-node-3
