name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      yugabytedb:
        image: ghcr.io/yogendra/yb-gh-action-service
        ports:
        - 7000:7000
        - 9000:9000
        - 5433:5433
        - 9042:9042
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots -Dspring.jpa.hibernate.ddl-auto=create package
      - name: Create staging area
        run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/yogendra/yb-payment-api:latest

